// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "rian3903@gmail.com"
        },
        "license": {
            "name": "Internal Use Only",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/create": {
            "post": {
                "description": "Processes a new wallet transaction, updating the user's current balance and generating a transaction record.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Wallet Transaction  User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Insert your access external: Bearer \u003cexternal\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payload create wallet transaction user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transaction_dto.CreateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/transaction_dto.CreateTransactionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helper.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errs.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "helper.BadRequestResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "BAD_REQUEST"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/errs.FieldError"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "validation error"
                }
            }
        },
        "helper.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "helper.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "SUCCESS"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "transaction.Status": {
            "type": "string",
            "enum": [
                "PENDING",
                "SUCCESS",
                "FAILED",
                "REVERSED"
            ],
            "x-enum-varnames": [
                "Pending",
                "Success",
                "Failed",
                "Reversed"
            ]
        },
        "transaction.Type": {
            "type": "string",
            "enum": [
                "TOPUP",
                "PURCHASE",
                "REFUND"
            ],
            "x-enum-varnames": [
                "Topup",
                "Purchase",
                "Refund"
            ]
        },
        "transaction_dto.CreateTransactionRequest": {
            "type": "object",
            "required": [
                "amount",
                "description",
                "transactionType"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "transactionType": {
                    "enum": [
                        "TOPUP",
                        "PURCHASE",
                        "REFUND"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/transaction.Type"
                        }
                    ]
                }
            }
        },
        "transaction_dto.CreateTransactionResponse": {
            "type": "object",
            "properties": {
                "reference": {
                    "type": "string"
                },
                "transactionStatus": {
                    "$ref": "#/definitions/transaction.Status"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8082",
	BasePath:         "/transaction/v1",
	Schemes:          []string{"http", "https"},
	Title:            "E-Wallet API - Mobile/Web",
	Description:      "API Service untuk m_transaction dompet digital pengguna (Transaction).\nFitur mencakup: Transaction.\n<br/><b>Developer:</b> Muhammad Brilian Satria Utama\n<b>Environment:</b> Development",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
